### ISSUE TITLE
Confusing Stack Trace Error

### ISSUE THREAD

**Issue by kmahorker** [UCSB-CS56-Projects/cs56-utilities-cryptography#74]
Stack trace is printed for a case where an error dialog box is shown. This is confusing for the developers who expect a stack trace when a run-time error occurs, rather than when a dialog box prevents the user from taking this "dangerous" action. Reproduce error by switching to decrypt mode and attempting to keyGen. 

Trace:
java.lang.Exception
     [java]     at edu.ucsb.cs56.projects.utilities.cryptography.GUIActionMethod.checkMode(GUIActionMethod.java:49)
     [java]     at edu.ucsb.cs56.projects.utilities.cryptography.GUIActionMethod.BifidGenKey(GUIActionMethod.java:487)
     [java]     at edu.ucsb.cs56.projects.utilities.cryptography.CryptographyGUI.lambda$go$5(CryptographyGUI.java:292)

**Comment by aryamandas** [comment]
F17 OK (50 points)
